### ISSUE TITLE
Make thread safe

### ISSUE THREAD

**Issue by bogatykh** [expressmapper/ExpressMapper#34]
ExpressMapper is not thread safe.

Example:
```
An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at ExpressMapper.MappingService.CompileCollection[T,TN]() in c:\SourceCode\ExpressMapper\ExpressMapper NET40\MappingService.cs:line 504
   at ExpressMapper.MappingService.PreCompileCollection[T,TN]() in c:\SourceCode\ExpressMapper\ExpressMapper NET40\MappingService.cs:line 493
   at ExpressMapper.MappingService.Map[T,TN](T src) in c:\SourceCode\ExpressMapper\ExpressMapper NET40\MappingService.cs:line 156
```

**Comment by anisimovyuriy** [comment]
FIXED and will be included in 1.1 release
