### ISSUE TITLE
Can't map to Destination Object (v1.5.0)

### ISSUE THREAD

**Issue by Molibar** [expressmapper/ExpressMapper#49]
Here's a unit test for you:

    [TestFixture]
    public class Tests
    {
        [Test]
        public void Should_map_Thing()
        {
            Mapper.Register<Thing, Thing>();
            var src = new Thing { Name = "Name" };
            var dest = new Thing();
            var result = Mapper.Map(src, dest, src.GetType(), dest.GetType())
                as Thing;
            Assert.That(result.Name, Is.EqualTo(src.Name));
        }
        internal class Thing { public string Name { get; set; } } 
    }

**Comment by Molibar** [comment]
System.NullReferenceException was unhandled by user code
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=Anonymously Hosted DynamicMethods Assembly
  StackTrace:
       at lambda_method(Closure , Thing , Thing )
       at ExpressMapper.TypeMapperBase`2.MapTo(T src, TN dest) in C:\SourceCode\ExpressMapper\ExpressMapper NET40\TypeMapperBase.cs:line 218
       at lambda_method(Closure , Object )
       at ExpressMapper.MappingServiceProvider.Map(Type srcType, Type dstType, Object src, Object dest) in C:\SourceCode\ExpressMapper\ExpressMapper NET40\MappingServiceProvider.cs:line 268
       at ExpressMapper.Mapper.Map(Object src, Object dest, Type srcType, Type dstType) in C:\SourceCode\ExpressMapper\ExpressMapper NET40\Mapper.cs:line 52
....

**Comment by anisimovyuriy** [comment]
Dear Molibar,
Thanks a lot for your input you are right there is a bug with non generic mapping with existing destination.
We'll fix it ASAP and release new version.

**Comment by anisimovyuriy** [comment]
Fixed, unit test was added and will be included in 1.6 release!

**Comment by Molibar** [comment]
Thanks, hero!
