### ISSUE TITLE
Problem with cloning of objects

### ISSUE THREAD

**Issue by pvlgk** [expressmapper/ExpressMapper#84]
I've problem with cloning objects.
My MappingRegistration code:
`            Mapper.Register<AppSettingsDTO, AppSettingsDTO>()
                .Member(dest => dest.SMTPPassword, src => src.SMTPPassword)
                .Member(dest => dest.SMTPPort, src => src.SMTPPort)
                .Member(dest => dest.SMTPServer, src => src.SMTPServer)
                .Member(dest => dest.SMTPUser, src => src.SMTPUser)
                .Member(dest => dest.Url, src => src.Url);

            Mapper.Compile();`

Compile method throws an exception:
ExpressMapper.ExpressmapperException was unhandled
  HResult=-2146233088
  Message=Error error occured trying to compile mapping for: source B7MBltuTransportPlanner.DataTransferObjects.AppSettingsDTO, destination B7MBltuTransportPlanner.DataTransferObjects.AppSettingsDTO. See the inner exception for details.
  Source=ExpressMapper
  StackTrace:
       at ExpressMapper.TypeMapperBase`2.Compile(CompilationTypes compilationType, Boolean forceByDemand) in C:\SourceCode\ExpressMapper\ExpressMapper NET40\TypeMapperBase.cs:line 108
       at ExpressMapper.MappingServiceBase.Compile(CompilationTypes compilationType) in C:\SourceCode\ExpressMapper\ExpressMapper NET40\MappingServiceBase.cs:line 36
       at ExpressMapper.MappingServiceProvider.Compile() in C:\SourceCode\ExpressMapper\ExpressMapper NET40\MappingServiceProvider.cs:line 107
       at ExpressMapper.Mapper.Compile() in C:\SourceCode\ExpressMapper\ExpressMapper NET40\Mapper.cs:line 18
       at B7MBltuTransportPlanner.App.InitializeAutoMapper() in D:\visual_c\Transport\B7MBltuTransportPlanner\B7MBltuTransportPlanner\App.xaml.cs:line 82
       at B7MBltuTransportPlanner.App.OnStartup(StartupEventArgs e) in D:\visual_c\Transport\B7MBltuTransportPlanner\B7MBltuTransportPlanner\App.xaml.cs:line 25
       at System.Windows.Application.<_ctor>b__0(Object unused)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.DispatcherOperation.InvokeImpl()
       at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Windows.Threading.DispatcherOperation.Invoke()
       at System.Windows.Threading.Dispatcher.ProcessQueue()
       at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
       at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
       at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
       at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
       at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
       at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
       at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
       at System.Windows.Application.RunDispatcher(Object ignore)
       at System.Windows.Application.RunInternal(Window window)
       at System.Windows.Application.Run(Window window)
       at System.Windows.Application.Run()
       at B7MBltuTransportPlanner.App.Main() in D:\visual_c\Transport\B7MBltuTransportPlanner\B7MBltuTransportPlanner\obj\Debug\App.g.cs:line 0
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146233069
       Message=No parameterless constructor defined for this object.
       Source=mscorlib
       StackTrace:
            at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
            at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
            at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
            at System.Activator.CreateInstance(Type type, Boolean nonPublic)
            at System.Activator.CreateInstance(Type type)
            at ExpressMapper.MappingServiceBase.GetMapExpressions(Type src, Type dest) in C:\SourceCode\ExpressMapper\ExpressMapper NET40\MappingServiceBase.cs:line 58
            at ExpressMapper.SourceMappingService.MapProperty(Type srcType, Type destType, Expression srcExpression, Expression destExpression, Boolean newDest) in C:\SourceCode\ExpressMapper\ExpressMapper NET40\SourceMappingService.cs:line 84
            at ExpressMapper.MappingServiceBase.GetDifferentTypeMemberMappingExpression(Expression srcExpression, Expression destExpression, Boolean newDest) in C:\SourceCode\ExpressMapper\ExpressMapper NET40\MappingServiceBase.cs:line 312
            at ExpressMapper.MappingServiceBase.GetMemberMappingExpression(Expression left, Expression right, Boolean newDest) in C:\SourceCode\ExpressMapper\ExpressMapper NET40\MappingServiceBase.cs:line 185
            at ExpressMapper.TypeMapperBase`2.MapMember(MemberExpression left, Expression right) in C:\SourceCode\ExpressMapper\ExpressMapper NET40\TypeMapperBase.cs:line 209
            at ExpressMapper.TypeMapperBase`2.AutoMapProperty(MemberInfo propertyGet, MemberInfo propertySet) in C:\SourceCode\ExpressMapper\ExpressMapper NET40\TypeMapperBase.cs:line 188
            at ExpressMapper.TypeMapperBase`2.ProcessAutoProperties() in C:\SourceCode\ExpressMapper\ExpressMapper NET40\TypeMapperBase.cs:line 266
            at ExpressMapper.SourceTypeMapper`2.CompileInternal() in C:\SourceCode\ExpressMapper\ExpressMapper NET40\SourceTypeMapper.cs:line 41
            at ExpressMapper.TypeMapperBase`2.Compile(CompilationTypes compilationType, Boolean forceByDemand) in C:\SourceCode\ExpressMapper\ExpressMapper NET40\TypeMapperBase.cs:line 104
       InnerException: 

Class AppSettingsDTO has got a contructor:
`public AppSettingsDTO()
        {

        }`

**Comment by anisimovyuriy** [comment]
Dear @pvlgk,

Thanks for your input! Just one simple question- what version of ExpressMapper do you use?

Thanks!

**Comment by anisimovyuriy** [comment]
Dear @pvlgk,

Thanks for your input! Just one simple question- what version of ExpressMapper do you use?

Thanks!

**Comment by pvlgk** [comment]
I use version 1.8.0

**Comment by anisimovyuriy** [comment]
Dear @pvlgk,

Sorry for the delay.
Ok I have more questions then:

1. What is the host platform you are trying to execute into? (WPF, Silverlight, WhondowsPhone)

2. It doesn't affect but you don't need to use ```.Member``` there as property names are the same on both sides

3. Do you have just flat properties? like "SMTPPassword {get;set;}"

Thanks!

**Comment by pvlgk** [comment]
Ad 1. WPF
Ad 2. Yes, I know. But I tried all the possibilities with the same result.
Ad 3. No. I have got one calculated property. Moreover the properties are decorated with attribute defined by me.

    public class AppSettingsDTO : AbstractDTO
    {
        private static string salt = "secret_word";

        public AppSettingsDTO()
        {

        }

        [B7MXMLElement("Url")]
        public string Url { get; set; }

        [B7MXMLElement("SMTPServer")]
        public string SMTPServer { get; set; }

        [B7MXMLElement("SMTPPort")]
        public int SMTPPort { get; set; }

        [B7MXMLElement("SMTPAuthRequired")]
        public bool SMTPAuthRequired { get; set; }

        public string SMTPUser { get; set; }
        public string SMTPPassword { get; set; }

        [B7MXMLElement("SMTPPassword")]
        public string SMTPPasswordEncrypted
        {
            get
            {
                if (String.IsNullOrEmpty(SMTPPassword))
                    return String.Empty;
                return StringCipher.Encrypt(SMTPPassword, salt);
            }
            set
            {
                if (!String.IsNullOrEmpty(value))
                {
                    SMTPPassword = StringCipher.Decrypt(value, salt);
                }
            }
        }
}

**Comment by anisimovyuriy** [comment]
Let me try to reproduce it. Meanwhile can you try use ```.Ignore``` for ```SMTPPasswordEncrypted``` property just for the sake of test.

Thanks @pvlgk !

**Comment by pvlgk** [comment]
For the purpose I removed attribute decorations and I tried:
            Mapper.Register<AppSettingsDTO, AppSettingsDTO>()
                .Ignore(dest => dest.SMTPPasswordEncrypted);

But `Mapper.Compile()` still fails.
Regards.

**Comment by rolandoldengarm** [comment]
I have got the same issue, how can I resolve this? In my case I've got a parameter in my model called "Numbers", type ICollection<MyNumber> and the source contains Numbers as well.
I've defined Numbers in my Dest() override, no luck.

**Comment by rolandoldengarm** [comment]
I've fixed this by renaming "Numbers" to "Numberssss" in my target model.
It's a shame that the related issue re Dest() not working when source & target still has not been fixed! This has cost me a couple of hours to debug.
To stay ahead of the game, such issues have to be fixed sooner... Or people will switch to e.g. AutoMapper. I'm still defending EM in my team, but not if such major issues remain unfixed.

**Comment by rolandoldengarm** [comment]
Okay, sorry @anisimovyuriy but this is taking too long, there's even no reply here :|. 
Along with the fact that EM is still not compatible with .NET Core we are now investigating to replace EM with another one. A big shame!

**Comment by anisimovyuriy** [comment]
Thanks for your response @rolandoldengarm  - and appreciated - well deserved :) !!!
I will fix it in a couple of days! Meanwhile enjoy .Net core in Expressmapper 1.8.2.
Please let me know if you have any questions for .Net Core Support!

**Comment by AmeetAB** [comment]
Hi, just a little feedback from what I have experienced using the package:
I have registered mapping between two objects - 
```
public class Product
{
    public string Code { get; set; }
}

public class ProductViewModel
{
    public Guid Code { get; set; }
}
```

the Mapper.Compile() method throws a "Parameterless constructor not found on object" which is totally misleading. Fair play that I haven't specified a conversion for that member but the error message has to be precise. My big problem is the error message which is no way near what the real problem is. or is it? Please shed some light.
